### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Braunson** [whoan/laravel-bash-helpers#1]
When trying to install these I'm receiving this..

```
-bash: /home/vagrant/laravel-bash-helpers/laravel-bash-helpers.sh: line 30: syntax error near unexpected token `('
-bash: /home/vagrant/laravel-bash-helpers/laravel-bash-helpers.sh: line 30: `artisan() {'
```

**Comment by whoan** [comment]
Just to try... What happens if you execute `unset -f artisan` previously to installing the script?
I am thinking it could be a problem with a previously definition of `artisan`. In fact, _homestead_ defines it [here](https://github.com/laravel/homestead/blob/master/src/stubs/aliases).

I can't reproduce the eror.

**Comment by Braunson** [comment]
I ran `unset -f artisan` without any feedback, then installed the script and when running `source "$pathlbs"` I received the same error above.

I even tried clearing out any previous aliases (including homestead's) and reloading the bashrc/bash_alises with the same error occurring. hmm

**Edit**: Figured it out, had to remove `.bash_aliases`, and restart (weird source ~./bashrc didn't reload any config).
